
from pydantic import BaseModel

from .briefing_stats_schema import BriefingStatsSchema


class DailyBriefingResponse(BaseModel):
    model_config = {"from_attributes": True}

    general_outlook: str
    impacted_assets: list[str]
    cautionary_hours: list[str]
    statistics: BriefingStatsSchema
    ai_disclaimer: str = (
        "Analysis generated by AI. Financial decisions are your own responsibility."
    )
