"""Initial schema

Revision ID: 3de8543205ef
Revises:
Create Date: 2026-03-09 11:42:25.648364

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3de8543205ef"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_alerts_user_id_users"), "users", ["user_id"], ["id"]
        )

    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_device_tokens_user_id_users"), "users", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device_tokens", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_device_tokens_user_id_users"), type_="foreignkey")

    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_alerts_user_id_users"), type_="foreignkey")

    # ### end Alembic commands ###
